### ISSUE TITLE
Does the process of `process_watcher` never stop?

### ISSUE THREAD

**Issue by Zhenye-Na** [arlowhite/process-watcher#4]
Hi @arlowhite ,

This is Zion here. I came across this wonderful repo from StackOverflow. This project is very interesting and meets our use case. Thank you so much for bringing this project and keep support it.

However, I am wondering if there is a way to monitor the `process_watcher` process itself? Since I am using this service to monitoring the webhook server I have for some automation process. I am wondering if the `process_watcher` could be as stable as it can so that we don't miss the notifications.

Maybe ?

```
process_watcher --pid <pid_of_previous_process_watcher>
```

Also, I did not figure out how to use the `command_regex` to monitor the process name. Suppose I have a python file called `webhook_server.py` and I run

```
nohup python3 webhook_server.py &
```

to make it run in the background.

When I run

```
process_watcher -c webhook_server
```

it seems that it is not been monitored. Would you mind sharing some tricks / tips on using it?

Thank you so much!!!!

**Comment by arlowhite** [comment]
Sorry for not replying sooner, I haven't been active on GitHub recently.

The -c command looks at `/proc/<PID>/cmdline`
so check if the .py suffix is in that file or not.
If cmdline is empty, it fallsback to `/proc/<PID>/comm`

As far as keeping process_watcher going, that's probably best handled by SystemD
https://www.digitalocean.com/community/tutorials/systemd-essentials-working-with-services-units-and-the-journal

I think you want `Restart=on-failure` or `Restart=always`
https://singlebrook.com/2017/10/23/auto-restart-crashed-service-systemd/
But I only have basic experience with SystemD

Honestly, SystemD is probably better than using `process_watcher` for your webhook_server in the first place. But, it does take some effort to learn and some careful setup. But you should be able to configure SystemD to notify you if the service crashes using `OnFailure`
